version: "3.8"

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME:-mirza_pro}_app
    build:
      context: .
      dockerfile: Dockerfile
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      TZ: ${TZ:-Asia/Tehran}
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT:-/var/www/html}
      # PHP runtime
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-64M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-64M}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-120}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS:-3000}
      PHP_OPCACHE_ENABLE: ${PHP_OPCACHE_ENABLE:-1}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${PHP_OPCACHE_MEMORY_CONSUMPTION:-128}
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: ${PHP_OPCACHE_INTERNED_STRINGS_BUFFER:-16}
      PHP_OPCACHE_MAX_ACCELERATED_FILES: ${PHP_OPCACHE_MAX_ACCELERATED_FILES:-10000}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-1}
      PHP_OPCACHE_REVALIDATE_FREQ: ${PHP_OPCACHE_REVALIDATE_FREQ:-2}
      # App config passed to PHP (read via getenv in config.php)
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      API_KEY: ${API_KEY:-}
      ADMIN_NUMBER: ${ADMIN_NUMBER:-}
      DOMAIN_NAME: ${DOMAIN_NAME:-}
      BOT_USERNAME: ${BOT_USERNAME:-}
      NEW_MARZBAN: ${NEW_MARZBAN:-true}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: ${COMPOSE_PROJECT_NAME:-mirza_pro}_db
    image: ${DB_IMAGE:-mariadb:10.11}
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ:-Asia/Tehran}
    ports:
      - "${DB_PORT_EXTERNAL:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
